apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testhttpd
  namespace: sandbox
spec:
  project: default
  source:
    repoURL: https://github.com/dulltz/test-apps.git
    targetRevision: master
    path: testhttpd
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
