apiVersion: apps/v1
kind: Deployment
metadata:
  name: testhttpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: testhttpd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: testhttpd
    spec:
      containers:
        - image: quay.io/cybozu/testhttpd:0
          name: testhttpd
      restartPolicy: Always
